language: cpp

compiler:
  - clang
  - gcc

sudo: false

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - cmake
      - clang-3.6
      - g++-5

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

script:
  - wget https://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py && find . -name *.h -o -name *.cc | xargs python cpplint.py
  - cd build && cmake .. && make && spec/ccspec_spec

cache: ccache

os:
  - linux
  - osx

notifications:
  email: false
